//! Web / phishing protection via a portable hosts-file blocklist.
//!
//! Malicious and phishing domains from our (signed) threat-intel feed are mapped
//! to a dead address in the OS hosts file, so they never resolve - on every
//! platform, entirely locally, with no cloud lookups (unlike the big suites,
//! which send every URL you visit to their servers).

use std::path::PathBuf;

const BEGIN: &str = "# >>> AetherAV web protection >>>";
const END: &str = "# <<< AetherAV web protection <<<";
const SINK: &str = "0.0.0.0";

/// The OS hosts-file path.
pub fn hosts_path() -> PathBuf {
    if cfg!(target_os = "windows") {
        // Honor SystemRoot if set, else the conventional location.
        let root = std::env::var("SystemRoot").unwrap_or_else(|_| "C:\\Windows".into());
        PathBuf::from(format!("{root}\\System32\\drivers\\etc\\hosts"))
    } else {
        PathBuf::from("/etc/hosts")
    }
}

fn normalize(domain: &str) -> Option<String> {
    let d = domain.trim().trim_end_matches('.').to_lowercase();
    // Drop scheme / path if a URL slipped in; keep the host.
    let d = d.split("://").last().unwrap_or(&d);
    let d = d.split('/').next().unwrap_or(d);
    let d = d.split(':').next().unwrap_or(d); // strip :port
    if d.is_empty() || !d.contains('.') || d.contains(' ') {
        return None;
    }
    Some(d.to_string())
}

/// Render the managed block that goes between our markers in the hosts file.
/// Each domain is sinkholed for both the bare name and its `www.` form.
pub fn render_block(domains: &[&str]) -> String {
    let mut seen = std::collections::BTreeSet::new();
    for d in domains {
        if let Some(n) = normalize(d) {
            seen.insert(n);
        }
    }
    let mut s = String::new();
    s.push_str(BEGIN);
    s.push('\n');
    s.push_str("# Generated by AetherAV - malicious/phishing domains, sinkholed locally.\n");
    for d in &seen {
        s.push_str(&format!("{SINK} {d}\n"));
        if !d.starts_with("www.") {
            s.push_str(&format!("{SINK} www.{d}\n"));
        }
    }
    s.push_str(END);
    s.push('\n');
    s
}

/// Merge a freshly rendered block into existing hosts-file text, replacing any
/// previous AetherAV-managed block. Pure - does not touch the filesystem.
pub fn merge_into_hosts(existing: &str, block: &str) -> String {
    let mut out = String::new();
    let mut skipping = false;
    for line in existing.lines() {
        if line.trim() == BEGIN {
            skipping = true;
            continue;
        }
        if line.trim() == END {
            skipping = false;
            continue;
        }
        if !skipping {
            out.push_str(line);
            out.push('\n');
        }
    }
    // Trim trailing blank lines, then append our block.
    while out.ends_with("\n\n") {
        out.pop();
    }
    if !out.is_empty() && !out.ends_with('\n') {
        out.push('\n');
    }
    out.push_str(block);
    out
}

/// Write the blocklist into the live hosts file (needs admin/root).
pub fn apply(domains: &[&str]) -> std::io::Result<usize> {
    let path = hosts_path();
    let existing = std::fs::read_to_string(&path).unwrap_or_default();
    let block = render_block(domains);
    let merged = merge_into_hosts(&existing, &block);
    std::fs::write(&path, merged)?;
    // Count sinkholed names (excludes the marker/comment lines).
    Ok(block.lines().filter(|l| l.starts_with(SINK)).count())
}

/// Remove the AetherAV-managed block from the hosts file (needs admin/root).
pub fn clear() -> std::io::Result<()> {
    let path = hosts_path();
    let existing = std::fs::read_to_string(&path).unwrap_or_default();
    let merged = merge_into_hosts(&existing, "");
    std::fs::write(&path, merged.trim_end().to_string() + "\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_sinkholes_and_dedups() {
        let b = render_block(&["evil.com", "Evil.com", "http://phish.net/login", "bad"]);
        assert!(b.contains("0.0.0.0 evil.com"));
        assert!(b.contains("0.0.0.0 www.evil.com"));
        assert!(b.contains("0.0.0.0 phish.net")); // URL reduced to host
        assert_eq!(b.matches("0.0.0.0 evil.com\n").count(), 1); // case-dedup
        assert!(!b.contains(" bad\n")); // no dot -> rejected
    }

    #[test]
    fn merge_replaces_previous_block_and_keeps_user_lines() {
        let host0 = "127.0.0.1 localhost\n";
        let m1 = merge_into_hosts(host0, &render_block(&["a.com"]));
        assert!(m1.contains("127.0.0.1 localhost"));
        assert!(m1.contains("0.0.0.0 a.com"));
        // Applying a new list must not stack old entries.
        let m2 = merge_into_hosts(&m1, &render_block(&["b.com"]));
        assert!(m2.contains("0.0.0.0 b.com"));
        assert!(!m2.contains("0.0.0.0 a.com"));
        assert!(m2.contains("127.0.0.1 localhost"));
        assert_eq!(m2.matches(BEGIN).count(), 1);
    }

    #[test]
    fn merge_empty_block_removes_managed_section() {
        let m1 = merge_into_hosts("127.0.0.1 localhost\n", &render_block(&["a.com"]));
        let cleared = merge_into_hosts(&m1, "");
        assert!(!cleared.contains("a.com"));
        assert!(!cleared.contains(BEGIN));
        assert!(cleared.contains("127.0.0.1 localhost"));
    }
}
